var q = [
  "This is what you shall do; Love the earth and sun and the animals, despise riches, give alms to every one that asks, stand up for the stupid and crazy, devote your income and labor to others, hate tyrants, argue not concerning God, have patience and indulgence toward the people, take off your hat to nothing known or unknown or to any man or number of men, go freely with powerful uneducated persons and with the young and with the mothers of families, read these leaves in the open air every season of every year of your life, re-examine all you have been told at school or church or in any book, dismiss whatever insults your own soul, and your very flesh shall be a great poem and have the richest fluency not only in its words but in the silent lines of its lips and face and between the lashes of your eyes and in every motion and joint of your body.",
  "I exist as I am, that is enough, If no other in the world be aware I sit content, And if each and all be aware I sit content. One world is aware, and by the far the largest to me, and that is myself, And whether I come to my own today or in ten thousand or ten million years, I can cheerfully take it now, or with equal cheerfulness, I can wait.",
  "I think I could turn and live with the animals, they are so placid and self contained; I stand and look at them long and long. They do not sweat and whine about their condition; They do not lie awake in the dark and weep for their sins; They do not make me sick discussing their duty to God; Not one is dissatisfied-not one is demented with the mania of owning things; Not one kneels to another, nor his kind that lived thousands of years ago; Not one is responsible or industrious over the whole earth.",
  "Whoever you are, now I place my hand upon you. That you may be my poem. I whisper with my lips close to your ear. I have loved many women and men, but I love none better than you.",
  "Afoot and lighthearted I take to the open road, healthy, free, the world before me. The long brown path before me leading me wherever I choose. Henceforth, I ask not good fortune, I myself am good fortune. Henceforth, I whimper no more, postpone no more, need nothing.",
  "All beauty comes from beautiful blood and a beautiful brain. If the greatnesses are in conjunction in a man or woman it is enough...the fact will prevail through the universe...but the gaggery and gilt of a million years will not prevail. Who troubles himself about his ornaments or fluency is lost. This is what you shall so: Love the earth and sun and the animals, despise riches, give alms to every one that asks, stand up for the stupid and crazy, devote your income and labor to others, hate tyrants, argue not concerning God, have patience and indulgence toward the people, take off your hat to nothing known or unknown or to any man or number of men, go freely with powerful uneducated persons and with the young and with the mothers of families, read these leaves in the open air every season of every year of your life, re-examine all you have been told at school or church or in any book, dismiss whatever insults your own soul, and your very flesh shall be a great poem and have the richest fluency not only in its words but in the silent lines of its lips and face and between the lashes of your eyes and in every motion and joint of your body...",
  "I bequeath myself to the dirt to grow from the grass I love. If you want me again look for me under your bootsoles. You will hardly know who I am or what I mean, but I shall be good help to you nevertheless, and filter and fiber your blood. Failing to fetch me at first keep encouraged, missing me one place search another, I stop some where waiting for you"
];

var quotes = function (){
  return q[Math.floor(Math.random()*q.length)];
  //return a RANDOM
};

module.exports.q = q;
module.exports.quotes = quotes;
